Repository GSG-FC03/Education-App, pull requests merged in 2021-08, with the labels that each got.

#12 writing README file
  README.md
Labels: awaiting review

#11 creating file structure
  assets/codewars.png
  assets/coursera.png
  assets/edu.png
  codeWarsPage/codeWars.css
  codeWarsPage/codeWars.html
  codeWarsPage/codeWars.js
  courseraPage/courseraPage.css
  courseraPage/courseraPage.html
  courseraPage/courseraPage.js
  homePage/home.css
  homePage/home.html
  homePage/home.js
  index.html
  landingPage/style.css
  signInGuestPage/signIn.css
  signInGuestPage/signIn.js
  signInGuestPage/singIn.html
  signUpPage/signUp.css
  signUpPage/signUp.html
  signUpPage/signUp.js
Labels: awaiting review

#22 Styling Home page elements
  homePage/home.css
  homePage/home.html
Labels: awaiting review

#21 2 creating landing page
  index.html
  landingPage/style.css
  signInGuestPage/signIn.css
  signInGuestPage/singIn.html
Labels: approved

#23 3 creating signin page
  signInGuestPage/signIn.css
  signInGuestPage/singIn.html
Labels: awaiting review

#24 6 creating codewars page
  codeWarsPage/codeWars.html
  codeWarsPage/codeWars.js
Labels: Draft, in-progress

#27 Create coursera page
  courseraPage/courseraPage.css
  courseraPage/courseraPage.html
  courseraPage/courseraPage.js
  courseraPage/data.json
  signInGuestPage/signIn.css
  signInGuestPage/singIn.html
Labels: awaiting review

#29 28 edit coursera style
  courseraPage/courseraPage.css
  courseraPage/courseraPage.html
  courseraPage/courseraPage.js
Labels: approved

#31 Deleting display property from logo class
  codeWarsPage/codeWars.css
Labels: approved

#25 3 create signin page
  signInGuestPage/signIn.css
  signInGuestPage/signIn.js
  signInGuestPage/singIn.html
Labels: approved

#34 32 editing styling pages
  homePage/home.css
  homePage/home.html
  signInGuestPage/signIn.css
  signInGuestPage/singIn.html
Labels: approved

#36 Editing README file
  README.md
Labels: approved
